### ISSUE TITLE
Move docs to new design

### ISSUE THREAD

**Issue by olasitarska** [django/djangoproject.com#102]
- [x] docs/doc.html
- [x] docs/genindex.html
- [x] docs/index.html
- [x] docs/py-modindex.html
- [x] docs/search.html
- [x] docs/search_form.html
- [x] version switcher (blocked by #116)
- [x] version chooser in search (blocked by #116)
- [x] horizontal navigation (next page, previous page) (blocked by #116)
