### ISSUE TITLE
Improving the organization of information - user research

### ISSUE THREAD

**Issue by thibaudcolas** [django/djangoproject.com#1495]
> Recommendations based on [user research report by 20tab](https://forum.djangoproject.com/t/at-what-point-is-the-work-on-the-ux-of-the-django-website/25981)

Some users complain of difficulty in finding specific information. Optimizing the information architecture and providing clear navigation could improve the ease of search and reduce pain points related to navigation.

```[tasklist]
## Tasks
- [ ] **Perform user testing**: Verify through usability testing what the actual navigation problems are.
- [ ] Add a site map in the footer for easier navigation
- [ ] Add search on all pages.
- [ ] **Improve Page Labelling**: Check and correct page titles to ensure consistency and clarity.
- [ ] **Conduct a card sorting workshop** with users to improve content per mapping
```

Related:

- #1411
- #1333
- #1347
- #404
