### ISSUE TITLE
Retire django-developers and django-users mailing list

### ISSUE THREAD

**Issue by thibaudcolas** [django/djangoproject.com#1727]
Following the forum thread ([Proposal: retiring django-users and django-developers mailing lists](https://forum.djangoproject.com/t/proposal-retiring-django-users-and-django-developers-mailing-lists/35747)), we can now move ahead with updating the website to remove or contextualize references to the django-developers and django-users mailing list. Corresponding Django ticket: [Retire django-developers and django-users mailing list django#35908](https://code.djangoproject.com/ticket/35908)

## Tasks

Here are relevant changes I think we should go ahead with:

- [x] In the footer, remove the `Django Users Mailing List` item
- [x] On the [Community](https://www.djangoproject.com/community/) page, remove the "Mailing Lists" section
- [x] On [Download / How to get Django](https://www.djangoproject.com/download/), replace "be sure to sign up for the django-users mailing list" with "be sure to sign up to the Django Forum"
- [x] On the [homepage](https://www.djangoproject.com/), remove the "Stay in the loop" section
- [ ] CoC-related pages

**Comment by bmispelon** [comment]
Would this change need to be released at the same time as the Django docs change, or can the two happen independently?

**Comment by thibaudcolas** [comment]
@bmispelon I think independently is good? We’re already in an inconsistent state where our content / docs showcase mailing lists that are under-utilised, so any intermediary change towards resolving that is a worthwhile improvement.

**Comment by bmispelon** [comment]
#1805 did almost all the work on this, but during the review we found out that the mailing lists are still mentionned on some CoC-related pages.

Since I wasn't sure whether changing these page required approval from the CoC workgroup, I decided to leave this issue open and ask the workgroup directly.

**Comment by thibaudcolas** [comment]
Excellent! :) Thank you both. I’ve added a "CoC-related pages" line item above.
